#!/usr/bin/env bash

if ! command -v brew >/dev/null 2>&1; then
    echo "Homebrew is not installed. Install homebrew and try again."
    exit 1
fi

# Shells
brew install bash
brew install zsh

# CLI tools
brew install git
brew install git-delta
brew install grep
brew install jq
brew install tree
brew install wget
brew install z

# Languages
brew install node
brew install python

# Helpers
brew install gh
brew install hugo
brew install terraform

# Cloud provider CLIs
brew install awscli
brew install azure-cli

# Apps
brew install --cask 1password
brew install --cask alfred
brew install --cask iterm2
brew install --cask rectangle
brew install --cask visual-studio-code

brew cleanup
