#!/usr/bin/env bash

if ! command -v brew >/dev/null 2>&1; then
    echo "Homebrew is not installed. Install homebrew and try again."
    exit 1
fi

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade

# Save Homebrew’s installed location.
BREW_PREFIX=$(brew --prefix)

# Install GNU core utilities (those that come with macOS are outdated).
brew install coreutils
ln -s "${BREW_PREFIX}/bin/gsha256sum" "${BREW_PREFIX}/bin/sha256sum"

# Shells
brew install bash
brew install zsh

# Git stuff
brew install git
brew install git-delta

# CLI tools
brew install ack
brew install bat
brew install gnu-sed
brew install grep
brew install jq
brew install openssh
brew install screen
brew install tree
brew install wget
brew install z

# Languages
brew install node
brew install python

# Helpers
brew install gh
brew install hugo
brew install terraform

# Cloud provider CLIs
brew install awscli
brew install azure-cli

# Apps
brew install --cask 1password
brew install --cask alfred
brew install --cask iterm2
brew install --cask rectangle
brew install --cask visual-studio-code

brew cleanup
