export PATH=/usr/local/bin:$(brew --prefix coreutils)/libexec/gnubin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin

export EDITOR=code

source $HOME/.zprezto/init.zsh
source $(brew --prefix)/etc/profile.d/z.sh

uptime

alias bubu='brew update && brew upgrade'
alias cat='bat'
alias dot='cd ~/Dropbox/dotfiles && $EDITOR .'
alias ll='tree -L 2'
alias m='git checkout master && git pull'
alias mkdirp='mkdir -p'
alias p='cd ~/Projects && ls'
alias c='code .'

export GOPATH=$HOME/gocode
export GOBIN=$GOPATH/bin
export GOROOT=/usr/local/opt/go/libexec

export PATH=$PATH:~/bin
export PATH=$PATH:$GOBIN
export PATH=$PATH:$GOROOT/bin
export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
export PATH=$HOME/.yarn/bin:$PATH
export PATH=/usr/local/opt/python/libexec/bin:$PATH

setopt CLOBBER
set -k
